# Generated by Django 5.0.12 on 2025-02-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodname', models.CharField(max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('kg', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='position',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='horse',
            name='father',
        ),
        migrations.RemoveField(
            model_name='horse',
            name='mother',
        ),
        migrations.RemoveField(
            model_name='horse',
            name='name',
        ),
        migrations.RemoveField(
            model_name='horse',
            name='origin',
        ),
        migrations.AddField(
            model_name='employee',
            name='birthdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='firstname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='lastname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='horse',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='horse',
            name='sex',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='horse',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='horse',
            name='breed',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
